title: Immer gutes Wetter!
email: hi@immerguteswetter.de
description: > # this means to ignore newlines until "baseurl:"
  Reiseblog von Verena und Flo
baseurl: ""
url: "https://immerguteswetter.de"

# Build settings
markdown: kramdown

# Use pretty URLs
permalink: pretty

exclude:
  - node_modules