title: Immer gutes Wetter!
email: hi@immerguteswetter.de
description: > # this means to ignore newlines until "baseurl:"
  Reiseblog von Verena und Flo
baseurl: ""
url: "https://immerguteswetter.de"

# Build settings
permalink: pretty
markdown: kramdown
highlighter: rouge
include: 
  - _pages
exclude:
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - "*.sublime-project"
  - "*.sublime-workspace"
  - tmp
  - LICENSE
  - README
  - .jekyll-asset-cache
  - .bundle
  - node_modules
